[2024-01-12T22:32:28.949+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_fdic_ncua.trigger_staging_dag manual__2024-01-12T22:31:36.254699+00:00 [queued]>
[2024-01-12T22:32:28.955+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_fdic_ncua.trigger_staging_dag manual__2024-01-12T22:31:36.254699+00:00 [queued]>
[2024-01-12T22:32:28.955+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 1
[2024-01-12T22:32:28.962+0000] {taskinstance.py:2192} INFO - Executing <Task(TriggerDagRunOperator): trigger_staging_dag> on 2024-01-12 22:31:36.254699+00:00
[2024-01-12T22:32:28.965+0000] {standard_task_runner.py:60} INFO - Started process 11312 to run task
[2024-01-12T22:32:28.969+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract_fdic_ncua', 'trigger_staging_dag', 'manual__2024-01-12T22:31:36.254699+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/fdic-ncua-ingest.py', '--cfg-path', '/tmp/tmpgztwhwkr']
[2024-01-12T22:32:28.970+0000] {standard_task_runner.py:88} INFO - Job 183: Subtask trigger_staging_dag
[2024-01-12T22:32:29.003+0000] {task_command.py:423} INFO - Running <TaskInstance: extract_fdic_ncua.trigger_staging_dag manual__2024-01-12T22:31:36.254699+00:00 [running]> on host c111cf247bc6
[2024-01-12T22:32:29.027+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:207: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2024-01-12T22:32:29.044+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extract_fdic_ncua' AIRFLOW_CTX_TASK_ID='trigger_staging_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-01-12T22:31:36.254699+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-12T22:31:36.254699+00:00'
[2024-01-12T22:32:29.053+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/trigger_dagrun.py", line 165, in execute
    dag_run = trigger_dag(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/api/common/trigger_dag.py", line 122, in trigger_dag
    raise DagNotFound(f"Dag id {dag_id} not found in DagModel")
airflow.exceptions.DagNotFound: Dag id fdic-ncua-staging not found in DagModel
[2024-01-12T22:32:29.056+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=extract_fdic_ncua, task_id=trigger_staging_dag, execution_date=20240112T223136, start_date=20240112T223228, end_date=20240112T223229
[2024-01-12T22:32:29.061+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 183 for task trigger_staging_dag (Dag id fdic-ncua-staging not found in DagModel; 11312)
[2024-01-12T22:32:29.066+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-12T22:32:29.076+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
